[package]
name = "fo_save_format"
version = "0.1.0"
authors = ["qthree <qthree3@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.2"
serdebug = "1.0"
bincode = "1.2"

[dev-dependencies]
ron = {version = "0.5"}
serde_json = "1.0"

[workspace]
members = ["cli"]
